version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: |
                sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
                echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
                sudo apt-get update
                sudo apt-get install mono-complete
                wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
                xbuild /p:Configuration=Release DummyNuget.sln

workflows:
    version: 2
    build_and_test:
        jobs:
            - build